import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { api, apiErrorMessage } from '../api/client';
import { Avatar } from '../components/Avatar';
import { useAuth } from '../context/AuthContext';

const choices = ['AI', 'Coding', 'Startups', 'Business', 'College', 'Gaming', 'Travel', 'Photography', 'Fitness', 'Music', 'Movies', 'Books', 'Design', 'Finance', 'Government Exams', 'Jobs', 'Sports'];
export function EditProfilePage() {
  const { user, verifiedCohorts, refreshMe } = useAuth(); const navigate = useNavigate();
  const [name, setName] = useState(user?.display_name ?? ''); const [avatarUrl, setAvatarUrl] = useState(user?.avatar_url ?? ''); const [bio, setBio] = useState(user?.bio ?? ''); const [interests, setInterests] = useState<string[]>(user?.interests ?? []); const [error, setError] = useState<string | null>(null); const [saving, setSaving] = useState(false);
  const cohort = verifiedCohorts.find((item) => item.is_primary) ?? verifiedCohorts[0];
  if (!user) return null;
  const toggle = (value: string) => setInterests((current) => current.includes(value) ? current.filter((item) => item !== value) : current.length < 15 ? [...current, value] : current);
  async function submit(e: FormEvent) { e.preventDefault(); setSaving(true); setError(null); try { await api.patch('/profile', { displayName: name, avatarUrl: avatarUrl || null, bio, interests }); await refreshMe(); navigate('/profile'); } catch (err) { setError(apiErrorMessage(err)); } finally { setSaving(false); } }
  return <div className="min-h-screen bg-paper"><main className="mx-auto max-w-2xl px-5 py-7"><Link to="/profile" className="text-sm font-semibold text-navy/60">← Back to profile</Link><form onSubmit={submit} className="mt-5 rounded-[2rem] bg-white p-6 shadow-sm ring-1 ring-navy/5 sm:p-8"><h1 className="font-display text-3xl font-semibold text-navy">Edit your profile</h1><p className="mt-2 text-sm leading-6 text-ink/60">Choose what your generation sees. Your private account details stay private.</p><div className="mt-7 flex items-center gap-4"><Avatar name={name || user.display_name} src={avatarUrl} size="sm"/><div className="flex-1"><label className="text-sm font-semibold text-navy">Profile photo URL</label><input type="url" value={avatarUrl} onChange={(e) => setAvatarUrl(e.target.value)} placeholder="https://…" className="mt-1 w-full rounded-xl border border-navy/15 px-3 py-2 text-sm"/></div></div><label className="mt-6 block text-sm font-semibold text-navy">Display name<input required maxLength={80} value={name} onChange={(e) => setName(e.target.value)} className="mt-1 w-full rounded-xl border border-navy/15 px-3 py-2.5 font-normal"/></label><label className="mt-5 block text-sm font-semibold text-navy">Bio<textarea maxLength={500} value={bio} onChange={(e) => setBio(e.target.value)} className="mt-1 min-h-28 w-full rounded-xl border border-navy/15 px-3 py-2.5 font-normal"/><span className="mt-1 block text-right text-xs font-normal text-ink/45">{bio.length}/500</span></label><div className="mt-5"><p className="text-sm font-semibold text-navy">Interests</p><div className="mt-3 flex flex-wrap gap-2">{choices.map((choice) => <button type="button" key={choice} onClick={() => toggle(choice)} className={`rounded-full px-3 py-2 text-sm transition ${interests.includes(choice) ? 'bg-navy text-paper' : 'bg-paper text-navy ring-1 ring-navy/10'}`}>{choice}</button>)}</div></div><div className="mt-7 space-y-2 rounded-2xl bg-paper p-4 text-sm text-ink/60"><p>🔒 Date of birth <span className="text-ink/40">• Private · Cannot normally be changed</span></p><p>📱 Phone number <span className="text-ink/40">• Private</span></p><p>🌍 Generation <span className="text-ink/40">• Automatically determined{cohort ? ` · ${cohort.label}` : ''}</span></p></div>{error && <p role="alert" className="mt-4 text-sm text-red-600">{error}</p>}<button disabled={saving} className="mt-6 w-full rounded-xl bg-navy py-3 text-sm font-semibold text-paper disabled:opacity-60">{saving ? 'Saving…' : 'Save changes'}</button></form></main></div>;
}
